// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movements.proto

#include "movements.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr MovementResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MovementResponse::MovementResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MovementResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovementResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovementResponseDefaultTypeInternal() {}
  union {
    MovementResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovementResponseDefaultTypeInternal _MovementResponse_default_instance_;

inline constexpr MovementRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : direction_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        distance_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR MovementRequest::MovementRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct MovementRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MovementRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MovementRequestDefaultTypeInternal() {}
  union {
    MovementRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MovementRequestDefaultTypeInternal _MovementRequest_default_instance_;
static ::_pb::Metadata file_level_metadata_movements_2eproto[2];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_movements_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_movements_2eproto = nullptr;
const ::uint32_t TableStruct_movements_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MovementRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MovementRequest, _impl_.direction_),
    PROTOBUF_FIELD_OFFSET(::MovementRequest, _impl_.distance_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::MovementResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::MovementResponse, _impl_.message_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::MovementRequest)},
        {10, -1, -1, sizeof(::MovementResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::_MovementRequest_default_instance_._instance,
    &::_MovementResponse_default_instance_._instance,
};
const char descriptor_table_protodef_movements_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017movements.proto\"6\n\017MovementRequest\022\021\n\t"
    "direction\030\001 \001(\t\022\020\n\010distance\030\002 \001(\005\"#\n\020Mov"
    "ementResponse\022\017\n\007message\030\001 \001(\t2>\n\017Moveme"
    "ntService\022+\n\004Move\022\020.MovementRequest\032\021.Mo"
    "vementResponseb\006proto3"
};
static ::absl::once_flag descriptor_table_movements_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_movements_2eproto = {
    false,
    false,
    182,
    descriptor_table_protodef_movements_2eproto,
    "movements.proto",
    &descriptor_table_movements_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_movements_2eproto::offsets,
    file_level_metadata_movements_2eproto,
    file_level_enum_descriptors_movements_2eproto,
    file_level_service_descriptors_movements_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_movements_2eproto_getter() {
  return &descriptor_table_movements_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_movements_2eproto(&descriptor_table_movements_2eproto);
// ===================================================================

class MovementRequest::_Internal {
 public:
};

MovementRequest::MovementRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MovementRequest)
}
inline PROTOBUF_NDEBUG_INLINE MovementRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : direction_(arena, from.direction_),
        _cached_size_{0} {}

MovementRequest::MovementRequest(
    ::google::protobuf::Arena* arena,
    const MovementRequest& from)
    : ::google::protobuf::Message(arena) {
  MovementRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.distance_ = from._impl_.distance_;

  // @@protoc_insertion_point(copy_constructor:MovementRequest)
}
inline PROTOBUF_NDEBUG_INLINE MovementRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : direction_(arena),
        _cached_size_{0} {}

inline void MovementRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.distance_ = {};
}
MovementRequest::~MovementRequest() {
  // @@protoc_insertion_point(destructor:MovementRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MovementRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.direction_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MovementRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:MovementRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.direction_.ClearToEmpty();
  _impl_.distance_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MovementRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 33, 2> MovementRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MovementRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 distance = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(MovementRequest, _impl_.distance_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(MovementRequest, _impl_.distance_)}},
    // string direction = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MovementRequest, _impl_.direction_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string direction = 1;
    {PROTOBUF_FIELD_OFFSET(MovementRequest, _impl_.direction_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // int32 distance = 2;
    {PROTOBUF_FIELD_OFFSET(MovementRequest, _impl_.distance_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\17\11\0\0\0\0\0\0"
    "MovementRequest"
    "direction"
  }},
};

::uint8_t* MovementRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MovementRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string direction = 1;
  if (!this->_internal_direction().empty()) {
    const std::string& _s = this->_internal_direction();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MovementRequest.direction");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // int32 distance = 2;
  if (this->_internal_distance() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<2>(
            stream, this->_internal_distance(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MovementRequest)
  return target;
}

::size_t MovementRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MovementRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string direction = 1;
  if (!this->_internal_direction().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_direction());
  }

  // int32 distance = 2;
  if (this->_internal_distance() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_distance());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MovementRequest::_class_data_ = {
    MovementRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MovementRequest::GetClassData() const {
  return &_class_data_;
}

void MovementRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MovementRequest*>(&to_msg);
  auto& from = static_cast<const MovementRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MovementRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_direction().empty()) {
    _this->_internal_set_direction(from._internal_direction());
  }
  if (from._internal_distance() != 0) {
    _this->_internal_set_distance(from._internal_distance());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MovementRequest::CopyFrom(const MovementRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MovementRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MovementRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MovementRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MovementRequest::InternalSwap(MovementRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.direction_, &other->_impl_.direction_, arena);
        swap(_impl_.distance_, other->_impl_.distance_);
}

::google::protobuf::Metadata MovementRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_movements_2eproto_getter, &descriptor_table_movements_2eproto_once,
      file_level_metadata_movements_2eproto[0]);
}
// ===================================================================

class MovementResponse::_Internal {
 public:
};

MovementResponse::MovementResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:MovementResponse)
}
inline PROTOBUF_NDEBUG_INLINE MovementResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : message_(arena, from.message_),
        _cached_size_{0} {}

MovementResponse::MovementResponse(
    ::google::protobuf::Arena* arena,
    const MovementResponse& from)
    : ::google::protobuf::Message(arena) {
  MovementResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:MovementResponse)
}
inline PROTOBUF_NDEBUG_INLINE MovementResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : message_(arena),
        _cached_size_{0} {}

inline void MovementResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
MovementResponse::~MovementResponse() {
  // @@protoc_insertion_point(destructor:MovementResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void MovementResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.message_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void MovementResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:MovementResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.message_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* MovementResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2> MovementResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_MovementResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string message = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(MovementResponse, _impl_.message_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string message = 1;
    {PROTOBUF_FIELD_OFFSET(MovementResponse, _impl_.message_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\7\0\0\0\0\0\0"
    "MovementResponse"
    "message"
  }},
};

::uint8_t* MovementResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MovementResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    const std::string& _s = this->_internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "MovementResponse.message");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MovementResponse)
  return target;
}

::size_t MovementResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MovementResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 1;
  if (!this->_internal_message().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData MovementResponse::_class_data_ = {
    MovementResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* MovementResponse::GetClassData() const {
  return &_class_data_;
}

void MovementResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<MovementResponse*>(&to_msg);
  auto& from = static_cast<const MovementResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:MovementResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _this->_internal_set_message(from._internal_message());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void MovementResponse::CopyFrom(const MovementResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MovementResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool MovementResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* MovementResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void MovementResponse::InternalSwap(MovementResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
}

::google::protobuf::Metadata MovementResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_movements_2eproto_getter, &descriptor_table_movements_2eproto_once,
      file_level_metadata_movements_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
